Implement gro output for other systems than water
XzzX/mrmd pull request #23
Opened 2024-11-06 17:08 UTC by J-Hizzle

Changed the .gro file output to take residue name and atom type as user parameters, so that other systems than water may be printed to .gro files. Also wrote test and minimal example. However, output for water is somewhat broken at the moment due to indexing issues with residue sizes > 1. This would need to be reworked in the future.

2024-11-07 10:07 UTC, XzzX requested changes

2024-11-07 10:07 UTC, XzzX commented on examples/PrintAtomsToGro/PrintAtomsToGro.cpp
Does not provide more insight/help than [mrmd/io/DumpGRO.test.cpp](mrmd/io/DumpGRO.test.cpp). Nevertheless, the implementation is correct. If it does not add anything special I would remove it.

2024-11-07 10:07 UTC, XzzX commented on mrmd/io/DumpGRO.test.cpp
This is only a "does-it-compile" test which is better than before but does not really test anything. Please add a correct gro output file and check the contents for equality.

2024-11-07 10:43 UTC, XzzX commented
What happens if the strings exceed the character limit of 5? I am ok with either truncating it or throwing an error.

2024-11-07 10:58 UTC, J-Hizzle commented on examples/PrintAtomsToGro/PrintAtomsToGro.cpp
That's fair. We can remove it.

2024-11-07 10:59 UTC, J-Hizzle commented on mrmd/io/DumpGRO.test.cpp
Good point, I can add that.

2024-11-07 11:02 UTC, J-Hizzle commented on mrmd/io/DumpGRO.hpp
> +             std::vector<std::string> typeNames = {"OW1", "HW2", "HW3"}
Sounds reasonable to me. I can also work in the changes for the already present uses that call dumpGRO so that we don't break anything. This would necessitate another user parameter "atomsPerRes" so that output of molecules containing more than one atom (such as water) is still possible.

2024-11-07 11:05 UTC, J-Hizzle commented
> What happens if the strings exceed the character limit of 5? I am ok with either truncating it or throwing an error.

I would prefer throwing an error for clarity of use.

2024-11-07 11:09 UTC, J-Hizzle commented on mrmd/io/DumpGRO.cpp
> +        std::string typeName = typeNames[typ(idx)];
Why would we prefer pointers and const values here?

2024-11-07 11:11 UTC, J-Hizzle commented
We should link this PR to Issue #22. All my commits are also marked with it's number.

2024-11-07 13:21 UTC, XzzX commented on mrmd/io/DumpGRO.cpp
> +        std::string typeName = typeNames[typ(idx)];
Because otherwise the string will be deep copied every time this line is encountered.

2024-11-07 13:24 UTC, XzzX commented
> We should link this PR to Issue #22. All my commits are also marked with it's number.

https://docs.github.com/de/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue

2024-11-21 15:20 UTC, J-Hizzle commented on mrmd/io/DumpGRO.cpp
> +             std::vector<std::string> typeNames)
This produces an error during building on my computer:
> std::vector must have a non-const, non-volatile value_type
Does that happen to you as well?

2024-11-21 15:54 UTC, J-Hizzle commented on mrmd/io/DumpGRO.hpp
> +             std::vector<std::string> typeNames = {"OW1", "HW2", "HW3"}
Exactly!

2024-11-22 15:31 UTC, XzzX commented on mrmd/io/DumpGRO.cpp
> +             std::vector<std::string> typeNames)
`const std::vector<std::string>&` is enough. I was a little bit over eager there :D

2024-11-26 12:46 UTC, J-Hizzle commented on mrmd/io/DumpGRO.hpp
> +             std::vector<std::string> typeNames = {"OW1", "HW2", "HW3"}
Update: I would suggest to open a new issue for making the multi-atom-per-molecule .gro output work. As of now, this case in neither covered nor very important. Consequently, I commented out the dumpGRO calls in the SPC example, which is the only problematic call in the program I know of.

2024-11-26 12:59 UTC, J-Hizzle commented on examples/PrintAtomsToGro/PrintAtomsToGro.cpp
I removed it.

2024-11-26 13:08 UTC, J-Hizzle commented
> [https://github.com/XzzX/mrmd/pull/23#issuecomment-2462250266](url)

Now I'm reconsidering whether we should even through an error. Technically, we would need to check for all entries in the file whether they are correct, which could clutter the code a bit. Might it be more convenient to trust the user with this?

2024-11-26 13:11 UTC, J-Hizzle commented
> And we need to make sure all existing usages work correctly with the changes.

I updated all existing examples.

2024-11-26 16:52 UTC, XzzX commented on mrmd/io/DumpGRO.hpp
> +             std::vector<std::string> typeNames = {"OW1", "HW2", "HW3"}
ok

2024-11-26 17:01 UTC, XzzX commented
Now we have to solve the question why the CI is not running for this PR. Can you check in the settings of your fork if GitHub Actions are enabled?

2024-11-27 10:53 UTC, J-Hizzle commented on examples/Argon/MultiResArgon.cpp
> +            //            false);
No, you're right. I updated and reincluded it.

 :eyes: a66383357c6ffc347593e97e62aa33a8d77bbd43

2024-11-27 12:36 UTC, XzzX approved these changes

2024-11-27 15:44 UTC, merged